ARG CMONGO_VERSION=1.0b-13
ARG CERVER_VERSION=2.0b-46
ARG HIREDIS_VERSION=1.0.0
ARG CREDIS_VERSION=0.5.2

ARG BUILD_DEPS='ca-certificates libssl-dev gdb'

FROM ermiry/mongoc:builder

ARG BUILD_DEPS
RUN apt-get --allow-releaseinfo-change update && apt-get install -y ${BUILD_DEPS}

# cmongo
ARG CMONGO_VERSION
RUN mkdir /opt/cmongo && cd /opt/cmongo \
    && wget -q --no-check-certificate https://github.com/ermiry-com/cmongo/archive/${CMONGO_VERSION}.zip \
    && unzip ${CMONGO_VERSION}.zip \
    && cd cmongo-${CMONGO_VERSION} \
    && make -j4 && make install

# hiredis
ARG HIREDIS_VERSION
RUN mkdir /opt/hiredis && cd /opt/hiredis \
    && wget -O hiredis.tar.gz https://github.com/redis/hiredis/archive/v${HIREDIS_VERSION}.tar.gz \
    && tar xzf hiredis.tar.gz \
    && cd /opt/hiredis/hiredis-${HIREDIS_VERSION} \
    && make -j4 && make install

# cerver
ARG CERVER_VERSION
RUN mkdir /opt/cerver && cd /opt/cerver \
    && wget -q https://github.com/ermiry/cerver/archive/${CERVER_VERSION}.zip \
    && unzip ${CERVER_VERSION}.zip \
    && cd cerver-${CERVER_VERSION} \
    && make -j4 && make install

# credis
ARG CREDIS_VERSION
RUN mkdir /opt/credis && cd /opt/credis \
    && wget -q --no-check-certificate https://github.com/ermiry-com/credis/archive/${CREDIS_VERSION}.zip \
    && unzip ${CREDIS_VERSION}.zip \
    && cd credis-${CREDIS_VERSION} \
    && make -j4 && make install

RUN ldconfig

# worker
WORKDIR /home/worker

CMD ["/bin/bash"]
